#!/bin/bash

fold=$1

echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
echo START TRAINING
echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
python3 /data/pathology/projects/pathology-lung-TIL/nnUNet_v2/nnunetv2/run/run_training.py "$fold"

echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
echo TRAINING DONE, STOP
echo XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
echo TOTALLY DONE